apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bin-reborncloud-cluster
  region: ap-south-2
  version: "1.32"

vpc:
  # Use default or custom VPC; adjust if needed
  # We'll tag subnets later

nodeGroups:
  - name: reborncloud-bin-workers
    instanceType: t3.medium
    desiredCapacity: 2
    privateNetworking: true
    ssh:
      allow: true
      publicKeyName: elson_sbx_apsouth2
    tags:
      Name: "reborncloud-bin-workers"
