apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: privatebin-pvc
  namespace: privatebin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ebs-sc
